services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: claude-workflow-backend
    restart: unless-stopped
    environment:
      # Required: Set via Koyeb secrets
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Performance settings - adjusted for Koyeb
      - MAX_CONCURRENT_JOBS=2
      - PYTHONUNBUFFERED=1
      # Koyeb-specific: Use PORT env var if provided
      - PORT=${PORT:-8000}
    networks:
      - claude-network
    ports:
      - "8000:8000"
    # Removed resource limits - Koyeb manages this at instance level
    # Removed volume mounts for ephemeral storage concerns
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: claude-workflow-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      # Frontend environment variables can be added here if needed
      - BACKEND_URL=http://backend:8000
    networks:
      - claude-network
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

networks:
  claude-network:
    driver: bridge
