version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: claude-workflow-backend
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MAX_CONCURRENT_JOBS=3
      - PYTHONUNBUFFERED=1
    volumes:
      # Persist generated files
      - ./backend/brand-data:/app/backend/brand-data
      - ./backend/brief-outputs:/app/backend/brief-outputs
      - ./backend/draft-outputs:/app/backend/draft-outputs
      - ./backend/logs:/app/backend/logs
      - ./backend/instructions:/app/backend/instructions:ro
      - ./backend/data:/app/backend/data:ro
      # Claude Code configuration (needs to be writable for debug logs, history, etc.)
      - ~/.claude:/home/appuser/.claude
    networks:
      - claude-network
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: claude-workflow-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - claude-network
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  claude-network:
    driver: bridge

volumes:
  brand-data:
  brief-outputs:
  draft-outputs:
  logs:
