version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY:-}claude-workflow-backend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.backend
      cache_from:
        - ${DOCKER_REGISTRY:-}claude-workflow-backend:latest
    container_name: claude-workflow-backend
    restart: always
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-3}
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    volumes:
      # Use named volumes for better performance in production
      - brand-data:/app/backend/brand-data
      - brief-outputs:/app/backend/brief-outputs
      - draft-outputs:/app/backend/draft-outputs
      - logs:/app/backend/logs
      # Read-only config volumes
      - ./backend/instructions:/app/backend/instructions:ro
      - ./backend/data:/app/backend/data:ro
      # Claude CLI configuration
      - ~/.anthropic:/root/.anthropic:ro
    networks:
      - claude-network
    ports:
      - "127.0.0.1:8000:8000"  # Only expose to localhost (use reverse proxy)
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
        reservations:
          cpus: '4'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${DOCKER_REGISTRY:-}claude-workflow-frontend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.frontend
      cache_from:
        - ${DOCKER_REGISTRY:-}claude-workflow-frontend:latest
    container_name: claude-workflow-frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - claude-network
    ports:
      - "127.0.0.1:80:80"  # Only expose to localhost (use reverse proxy)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  claude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  brand-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/brand-data
  brief-outputs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/brief-outputs
  draft-outputs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/draft-outputs
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/logs
